@test_id = 5fecd438938c644ee85dbc00

@test_blog_id = 600855722c6fe91ed1b2ae26

@hostname = http://localhost:3001


### unknown endpoint

GET {{hostname}}/api/unknownendpoint HTTP/1.1

### get all blogs

GET {{hostname}}/api/blogs HTTP/1.1

### get one blog by id

GET {{hostname}}/api/blogs/{{test_blog_id}} HTTP/1.1

### create blog

POST {{hostname}}/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF2ZXJ5d2xpdHRsZSIsImlkIjoiNWZlY2Q0Mzg5MzhjNjQ0ZWU4NWRiYzAwIiwiaWF0IjoxNjA5MzYzMTc1fQ.N7kFoQbq3NdkuNYlMb44qNnQqt4JE3MLDZhWUZOdfHk

{
    "title": "Avery's Journal",
    "author": "Avery Little",
    "url": "www.averywlittle.com",
    "likes": 7,
    "userId": "5fecd438938c644ee85dbc00"
}

### edit blog

PUT {{hostname}}/api/blogs/{{test_blog_id}} HTTP/1.1
content-type: application/json

{
    "title": "Avery's Journal",
    "author": "Avery Little",
    "url": "www.averywlittle.com",
    "likes": 2
}

### edit blog comments

POST {{hostname}}/api/blogs/{{test_blog_id}}/comments HTTP/1.1
content-type: application/json

{
    "content": "ANOTHER comment" 
}

### delete blog

DELETE  {{hostname}}/api/blogs/{{test_id}} HTTP/1.1
content-type: application/application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF2ZXJ5d2xpdHRsZSIsImlkIjoiNWZlY2Q0Mzg5MzhjNjQ0ZWU4NWRiYzAwIiwiaWF0IjoxNjA5MzY0MjQxfQ.wr-Aa4LU_CN7Sqoc_AzmNaKUfaSQtLv8z5xbfnyeIeQ


### create user

POST {{hostname}}/api/users HTTP/1.1
content-type: application/json

{
    "username": "hahaha",
    "name": "Gilfoyle",
    "password": "testpassword",
    "blogs": []
}

### try to create invalid user

POST {{hostname}}/api/users HTTP/1.1
content-type: application/json

{
    "username": "jo",
    "name": "jesus",
    "password": "al"
}

### attempt login

POST {{hostname}}/api/login HTTP/1.1
content-type: application/json

{
    "username": "averywlittle",
    "password": "testpassword"
}

### get all users
GET {{hostname}}/api/users HTTP/1.1