@test_id = 5feceef3f6d76052f0bacf0a
@hostname = http://localhost:3001

### unknown endpoint

GET {{hostname}}/api/unknownendpoint HTTP/1.1

### get all blogs

GET {{hostname}}/api/blogs HTTP/1.1

### create blog

POST {{hostname}}/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF2ZXJ5d2xpdHRsZSIsImlkIjoiNWZlY2Q0Mzg5MzhjNjQ0ZWU4NWRiYzAwIiwiaWF0IjoxNjA5MzYzMTc1fQ.N7kFoQbq3NdkuNYlMb44qNnQqt4JE3MLDZhWUZOdfHk

{
    "title": "The Sierra Guide",
    "author": "Summer Varner",
    "url": "www.thesierraguide.com",
    "likes": 7,
    "userId": "5fecd438938c644ee85dbc00"
}

### edit blog

PUT {{hostname}}/api/blogs/{{test_id}} HTTP/1.1
content-type: application/json

{
    "title": "Avery's Journal",
    "author": "Avery Little",
    "url": "www.averywlittle.com",
    "likes": 7
}

### delete blog

DELETE  {{hostname}}/api/blogs/{{test_id}} HTTP/1.1
content-type: application/application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF2ZXJ5d2xpdHRsZSIsImlkIjoiNWZlY2Q0Mzg5MzhjNjQ0ZWU4NWRiYzAwIiwiaWF0IjoxNjA5MzY0MjQxfQ.wr-Aa4LU_CN7Sqoc_AzmNaKUfaSQtLv8z5xbfnyeIeQ

### get all blogs

GET {{hostname}}/api/users HTTP/1.1

### create user

POST {{hostname}}/api/users HTTP/1.1
content-type: application/json

{
    "username": "averywlittle",
    "name": "Avery Little",
    "password": "testpassword",
    "blogs": []
}

### try to create invalid user

POST {{hostname}}/api/users HTTP/1.1
content-type: application/json

{
    "username": "jo",
    "name": "jesus",
    "password": "al"
}

### attempt login

POST {{hostname}}/api/login HTTP/1.1
content-type: application/json

{
    "username": "averywlittle",
    "password": "testpassword"
}